Link to libatomic when needed
The check is copied from xrootd (cmake/XRootDSystemCheck.cmake)

Fixes link failures on some 32 bit architecture:

[100%] Linking CXX shared module libXrdS3-5.so
/usr/bin/cmake -E cmake_link_script CMakeFiles/XrdS3.dir/link.txt --verbose=1
/usr/bin/ld: CMakeFiles/XrdS3Obj.dir/src/S3File.cc.o: in function `std::__atomic_base<long long>::operator+=(long long)':
/usr/include/c++/14/bits/atomic_base.h:414:(.text+0x1194): undefined reference to `__atomic_fetch_add_8'
/usr/bin/ld: /usr/include/c++/14/bits/atomic_base.h:414:(.text+0x582c): undefined reference to `__atomic_fetch_add_8'
/usr/bin/ld: /usr/include/c++/14/bits/atomic_base.h:414:(.text+0x5844): undefined reference to `__atomic_fetch_add_8'
/usr/bin/ld: /usr/include/c++/14/bits/atomic_base.h:414:(.text+0x6130): undefined reference to `__atomic_fetch_add_8'
/usr/bin/ld: /usr/include/c++/14/bits/atomic_base.h:414:(.text+0x6144): undefined reference to `__atomic_fetch_add_8'
/usr/bin/ld: CMakeFiles/XrdS3Obj.dir/src/S3File.cc.o:/usr/include/c++/14/bits/atomic_base.h:414: more undefined references to `__atomic_fetch_add_8' follow
collect2: error: ld returned 1 exit status
/usr/bin/c++ -fPIC -g -O2 -ffile-prefix-map=/build/reproducible-path/xrootd-s3-http-0.1.8=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_TIME_BITS=64 -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Werror -g -Wl,--version-script=/build/reproducible-path/xrootd-s3-http-0.1.8/configs/export-lib-symbols -Wl,--dependency-file=CMakeFiles/XrdS3.dir/link.d -Wl,-z,relro -Wl,-z,now -Wl,--no-undefined -shared  -o libXrdS3-5.so CMakeFiles/XrdS3Obj.dir/src/CurlUtil.cc.o CMakeFiles/XrdS3Obj.dir/src/S3File.cc.o CMakeFiles/XrdS3Obj.dir/src/S3Directory.cc.o CMakeFiles/XrdS3Obj.dir/src/S3AccessInfo.cc.o CMakeFiles/XrdS3Obj.dir/src/S3FileSystem.cc.o "CMakeFiles/XrdS3Obj.dir/src/AWSv4-impl.cc.o" CMakeFiles/XrdS3Obj.dir/src/S3Commands.cc.o CMakeFiles/XrdS3Obj.dir/src/HTTPCommands.cc.o CMakeFiles/XrdS3Obj.dir/src/TokenFile.cc.o CMakeFiles/XrdS3Obj.dir/src/stl_string_utils.cc.o CMakeFiles/XrdS3Obj.dir/src/shortfile.cc.o CMakeFiles/XrdS3Obj.dir/src/logging.cc.o  -ldl /usr/lib/arm-linux-gnueabi/libXrdUtils.so /usr/lib/arm-linux-gnueabi/libXrdServer.so /usr/lib/arm-linux-gnueabi/libcurl.so -lcrypto /usr/lib/arm-linux-gnueabi/libtinyxml2.so.10.0.0
make[3]: *** [CMakeFiles/XrdS3.dir/build.make:116: libXrdS3-5.so] Error 1