Fix linking error on 32 bit architectures
undefined reference to `XrdOssDF::pgRead(void*, long, unsigned int, unsigned int*, unsigned long long)'
undefined reference to `XrdOssDF::pgWrite(void*, long, unsigned int, unsigned int*, unsigned long long)'

Xrootd is compiled using -D_FILE_OFFSET_BITS=64. This means that the
second parameter in pgRead/pgWrite, which is declared as off_t in
xrootd's headers, is a long long on 32 bit architectures. Without
-D_FILE_OFFSET_BITS=64 the off_t is a long and there is a mismatch
which leads to a linking error.

Add -D_FILE_OFFSET_BITS=64 to the compiler definitions so that the
compilation uses the same off_t definition as xrootd does during
compilation.